services:
  breeder_service:
    build: ./breeder-service
    container_name: breeder_microservice
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./breeder-service/:/app/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - PYTHONPATH=/app
      - URL_PREFIX=http://localhost:8080/api/v1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/app/private-pubsub.json
      - GCP_PROJECT_ID=prime-victory-437119-p7
      - REQUEST_TOPIC=breeder-info-request
      - RESPONSE_TOPIC=breeder-info-response
      - REQUEST_SUBSCRIPTION_NAME=breeder-info-request-sub
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    depends_on:
      - breeder_db

  breeder_db:
    image: postgres:12.1-alpine
    container_name: breeder_db
    volumes:
      - postgres_data_breeder:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=breeder_db_username
      - POSTGRES_PASSWORD=breeder_db_password
      - POSTGRES_DB=breeder_db_dev
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: breeder_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - movie_service
      - breeder_service

volumes:
  # postgres_data_movie:
  postgres_data_breeder:
